services:

  app:
    build:
      context: .
    entrypoint: /app/scripts/docker-entrypoint.sh
    command: pnpm run dev
    volumes:
      - .:/app:cached
    ports:
      - 3000:3000
      - 5555:5555
    tty: false
    stdin_open: true
