compatibility_date = "2023-01-11"

compatibility_flags = [ "streams_enable_constructors" ]

send_metrics = false

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "mydb"
database_id = "5ee37933-fde2-4420-bb63-63ab3496292c"
